import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ChartNoAxesColumn, Trophy, UsersRound } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  matches,
  tournament,
}: Readonly<{
  children: React.ReactNode;
  matches: React.ReactNode;
  tournament: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <Toaster />
        {/* <Image src={"/bg.png"} alt="bg" fill={true} className="object-cover blur-md brightness-50" /> */}
        <SidebarProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            {/* <PlayerProvider> */}
              {/* <AppSidebar /> */}
              <main className="w-full max-w-6xl mx-auto relative p-4">
                <Tabs defaultValue="leaderboard" className="bg-none">
                  <div className="w-full relative flex justify-between items-center">
                    <TabsList className="">
                      <TabsTrigger value="leaderboard">
                        <ChartNoAxesColumn /> Leaderboard
                      </TabsTrigger>
                      <TabsTrigger value="tournament">
                        <Trophy /> Tournament
                      </TabsTrigger>
                      <TabsTrigger value="matches">
                        <UsersRound />
                        Matches
                      </TabsTrigger>
                    </TabsList>
                    <Dialog>
                      <form>
                        <DialogTrigger asChild>
                          <Button>Тоглогч нэмэх</Button>
                        </DialogTrigger>
                        <DialogContent className="sm:max-w-[425px]">
                          <DialogHeader>
                            <DialogTitle>Тоглогч нэмэх</DialogTitle>
                            <DialogDescription>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, quam!</DialogDescription>
                          </DialogHeader>
                          {/* <TestForm /> */}
                        </DialogContent>
                      </form>
                    </Dialog>
                  </div>
                  <TabsContent value="leaderboard">{children}</TabsContent>
                  <TabsContent value="matches">{matches}</TabsContent>
                  <TabsContent value="tournament">{tournament}</TabsContent>
                </Tabs>
              </main>
            {/* </PlayerProvider> */}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
